#pragma once

#define LSWAP_APPLICATION_NAME       "lswap"
#define LSWAP_APPLICATION_CLASS_NAME LSWAP_APPLICATION_NAME "001"
#define LSWAP_VERSION_STRING         "2.0.windows"
#define LSWAP_CONFIGURATION_FILENAME "." LSWAP_APPLICATION_NAME "conf"
#define LSWAP_MUTEX_NAME             LSWAP_APPLICATION_NAME "-mutex"